application: unishared-gae
version: production
#version: staging
runtime: python27
threadsafe: true
api_version: 1

skip_files: |
  ^(.*/)?(
  (node_modules/.*)|
  )$

handlers:

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /font
  static_dir: static/font

- url: /partials
  static_dir: static/partials

- url: /lib
  static_dir: static/lib

- url: /.*
  script: main.app

builtins:
  - remote_api: on

libraries:
- name: jinja2
  version: latest

env_variables:
  GOOGLE_ANALYTICS_ACCOUNT_PRODUCTION: 'UA-31995478-4'
  GOOGLE_ANALYTICS_ACCOUNT_STAGING: 'UA-31995478-5'